probes:
  - name: api-core-health
    url:	https://api.xylex.ai/systems/health/main
    http_method: GET
    expectations:
      - field: StatusCode
        operation: Equals 
        value: "200"
    schedule:
      initial_delay: 0
      interval: 15
    alerts:
      - url: https://discord.com/api/webhooks/1262877118573052018/C9TRgwPFlj5swDaHmH5LUhQqryUYkJMRZdzSnrlLGkqVYr9XDPSL1R03EKpYwtP5YURE


  - name: api-discord-health
    url:	https://api.xylex.ai/internals/xylex_discord/ping
    http_method: GET
    expectations:
      - field: StatusCode
        operation: Equals 
        value: "200"
    schedule:
      initial_delay: 0
      interval: 15
    alerts:
      - url: https://discord.com/api/webhooks/1262877118573052018/C9TRgwPFlj5swDaHmH5LUhQqryUYkJMRZdzSnrlLGkqVYr9XDPSL1R03EKpYwtP5YURE