probes:
  - name: Prodzilla Github
    url: https://github.com/prodzilla/prodzilla
    http_method: GET
    expectations:
      - field: StatusCode
        operation: Equals 
        value: "404"
      - field: Body
        operation: Contains 
        value: "prodzilla"
    schedule:
      initial_delay: 5
      interval: 10
    alerts:
      - url: https://webhook.site/3b30d8e7-0f77-4ac8-a1e3-81c23281b948
  
  - name: Webhook Receiver Probe
    url:	https://webhook.site/3b30d8e7-0f77-4ac8-a1e3-81c23281b948 
    http_method: POST
    with:
      headers:
        x-on-behalf-of: Jeff
      body: '"{"test": true}"'
    expectations:
      - field: StatusCode
        operation: Equals 
        value: "200"
    schedule:
      initial_delay: 2
      interval: 60

stories:
  - name: Get IP Address Info User Flow
    steps:
      - name: get-ip
        url: https://api.ipify.org/?format=json
        http_method: GET
        expectations:
          - field: StatusCode
            operation: Equals 
            value: "200"
      - name: get-location
        url: https://ipinfo.io/149.167.5.69/geo # will use ${{ steps.get-ip.body.ip }} in future
        http_method: GET
        expectations:
          - field: StatusCode
            operation: Equals 
            value: "200"
    schedule:
      initial_delay: 5
      interval: 10
    alerts:
      - url: https://webhook.site/54a9a526-c104-42a7-9b76-788e897390d8 